version: "1.0"

environment:
  log_level: "info"
  log_file: "skylark.log"

models:
  openai:
    gpt-4:
      api_key: "${OPENAI_API_KEY}"
      temperature: 0.7
      max_tokens: 2000
      top_p: 0.9
    gpt-3.5-turbo:
      api_key: "${OPENAI_API_KEY}"
      temperature: 0.5
      max_tokens: 1000
      top_p: 0.9

tools:
  summarize:
    env:
      MAX_LENGTH: "1000"
      TIMEOUT: "30s"
  web_search:
    env:
      TIMEOUT: "30s"

workers:
  count: 4
  queue_size: 100

file_watch:
  debounce_delay: "500ms"
  max_delay: "2s"
  extensions:
    - ".md"

watch_paths:
  - "."
